/* Auto-generated by genmsg_cpp for file /home/root/ros/opticalflow_msgs/msg/OpticalSensor.msg */
#ifndef OPTICALFLOW_MSGS_MESSAGE_OPTICALSENSOR_H
#define OPTICALFLOW_MSGS_MESSAGE_OPTICALSENSOR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace opticalflow_msgs
{
template <class ContainerAllocator>
struct OpticalSensor_ {
  typedef OpticalSensor_<ContainerAllocator> Type;

  OpticalSensor_()
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , vx(0.0)
  , vy(0.0)
  , vz(0.0)
  , vicon_x(0.0)
  , vicon_y(0.0)
  , vicon_z(0.0)
  , vicon_vx(0.0)
  , vicon_vy(0.0)
  , vicon_vz(0.0)
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  {
  }

  OpticalSensor_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , vx(0.0)
  , vy(0.0)
  , vz(0.0)
  , vicon_x(0.0)
  , vicon_y(0.0)
  , vicon_z(0.0)
  , vicon_vx(0.0)
  , vicon_vy(0.0)
  , vicon_vz(0.0)
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _z_type;
  double z;

  typedef double _vx_type;
  double vx;

  typedef double _vy_type;
  double vy;

  typedef double _vz_type;
  double vz;

  typedef double _vicon_x_type;
  double vicon_x;

  typedef double _vicon_y_type;
  double vicon_y;

  typedef double _vicon_z_type;
  double vicon_z;

  typedef double _vicon_vx_type;
  double vicon_vx;

  typedef double _vicon_vy_type;
  double vicon_vy;

  typedef double _vicon_vz_type;
  double vicon_vz;

  typedef double _roll_type;
  double roll;

  typedef double _pitch_type;
  double pitch;

  typedef double _yaw_type;
  double yaw;


private:
  static const char* __s_getDataType_() { return "opticalflow_msgs/OpticalSensor"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "09c9896124e143c4ae0b4fda90de8eaf"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 x\n\
float64 y\n\
float64 z\n\
float64 vx\n\
float64 vy\n\
float64 vz\n\
float64 vicon_x\n\
float64 vicon_y\n\
float64 vicon_z\n\
float64 vicon_vx\n\
float64 vicon_vy\n\
float64 vicon_vz\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    ros::serialization::serialize(stream, z);
    ros::serialization::serialize(stream, vx);
    ros::serialization::serialize(stream, vy);
    ros::serialization::serialize(stream, vz);
    ros::serialization::serialize(stream, vicon_x);
    ros::serialization::serialize(stream, vicon_y);
    ros::serialization::serialize(stream, vicon_z);
    ros::serialization::serialize(stream, vicon_vx);
    ros::serialization::serialize(stream, vicon_vy);
    ros::serialization::serialize(stream, vicon_vz);
    ros::serialization::serialize(stream, roll);
    ros::serialization::serialize(stream, pitch);
    ros::serialization::serialize(stream, yaw);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    ros::serialization::deserialize(stream, z);
    ros::serialization::deserialize(stream, vx);
    ros::serialization::deserialize(stream, vy);
    ros::serialization::deserialize(stream, vz);
    ros::serialization::deserialize(stream, vicon_x);
    ros::serialization::deserialize(stream, vicon_y);
    ros::serialization::deserialize(stream, vicon_z);
    ros::serialization::deserialize(stream, vicon_vx);
    ros::serialization::deserialize(stream, vicon_vy);
    ros::serialization::deserialize(stream, vicon_vz);
    ros::serialization::deserialize(stream, roll);
    ros::serialization::deserialize(stream, pitch);
    ros::serialization::deserialize(stream, yaw);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    size += ros::serialization::serializationLength(z);
    size += ros::serialization::serializationLength(vx);
    size += ros::serialization::serializationLength(vy);
    size += ros::serialization::serializationLength(vz);
    size += ros::serialization::serializationLength(vicon_x);
    size += ros::serialization::serializationLength(vicon_y);
    size += ros::serialization::serializationLength(vicon_z);
    size += ros::serialization::serializationLength(vicon_vx);
    size += ros::serialization::serializationLength(vicon_vy);
    size += ros::serialization::serializationLength(vicon_vz);
    size += ros::serialization::serializationLength(roll);
    size += ros::serialization::serializationLength(pitch);
    size += ros::serialization::serializationLength(yaw);
    return size;
  }

  typedef boost::shared_ptr< ::opticalflow_msgs::OpticalSensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opticalflow_msgs::OpticalSensor_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct OpticalSensor
typedef  ::opticalflow_msgs::OpticalSensor_<std::allocator<void> > OpticalSensor;

typedef boost::shared_ptr< ::opticalflow_msgs::OpticalSensor> OpticalSensorPtr;
typedef boost::shared_ptr< ::opticalflow_msgs::OpticalSensor const> OpticalSensorConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::opticalflow_msgs::OpticalSensor_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::opticalflow_msgs::OpticalSensor_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace opticalflow_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::opticalflow_msgs::OpticalSensor_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::opticalflow_msgs::OpticalSensor_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::opticalflow_msgs::OpticalSensor_<ContainerAllocator> > {
  static const char* value() 
  {
    return "09c9896124e143c4ae0b4fda90de8eaf";
  }

  static const char* value(const  ::opticalflow_msgs::OpticalSensor_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x09c9896124e143c4ULL;
  static const uint64_t static_value2 = 0xae0b4fda90de8eafULL;
};

template<class ContainerAllocator>
struct DataType< ::opticalflow_msgs::OpticalSensor_<ContainerAllocator> > {
  static const char* value() 
  {
    return "opticalflow_msgs/OpticalSensor";
  }

  static const char* value(const  ::opticalflow_msgs::OpticalSensor_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::opticalflow_msgs::OpticalSensor_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 vx\n\
float64 vy\n\
float64 vz\n\
float64 vicon_x\n\
float64 vicon_y\n\
float64 vicon_z\n\
float64 vicon_vx\n\
float64 vicon_vy\n\
float64 vicon_vz\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
\n\
";
  }

  static const char* value(const  ::opticalflow_msgs::OpticalSensor_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::opticalflow_msgs::OpticalSensor_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::opticalflow_msgs::OpticalSensor_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.vx);
    stream.next(m.vy);
    stream.next(m.vz);
    stream.next(m.vicon_x);
    stream.next(m.vicon_y);
    stream.next(m.vicon_z);
    stream.next(m.vicon_vx);
    stream.next(m.vicon_vy);
    stream.next(m.vicon_vz);
    stream.next(m.roll);
    stream.next(m.pitch);
    stream.next(m.yaw);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct OpticalSensor_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opticalflow_msgs::OpticalSensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::opticalflow_msgs::OpticalSensor_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
    s << indent << "vz: ";
    Printer<double>::stream(s, indent + "  ", v.vz);
    s << indent << "vicon_x: ";
    Printer<double>::stream(s, indent + "  ", v.vicon_x);
    s << indent << "vicon_y: ";
    Printer<double>::stream(s, indent + "  ", v.vicon_y);
    s << indent << "vicon_z: ";
    Printer<double>::stream(s, indent + "  ", v.vicon_z);
    s << indent << "vicon_vx: ";
    Printer<double>::stream(s, indent + "  ", v.vicon_vx);
    s << indent << "vicon_vy: ";
    Printer<double>::stream(s, indent + "  ", v.vicon_vy);
    s << indent << "vicon_vz: ";
    Printer<double>::stream(s, indent + "  ", v.vicon_vz);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};


} // namespace message_operations
} // namespace ros

#endif // OPTICALFLOW_MSGS_MESSAGE_OPTICALSENSOR_H

