/* Auto-generated by genmsg_cpp for file /home/root/ros/opticalflow_msgs/msg/Traj.msg */
#ifndef OPTICALFLOW_MSGS_MESSAGE_TRAJ_H
#define OPTICALFLOW_MSGS_MESSAGE_TRAJ_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace opticalflow_msgs
{
template <class ContainerAllocator>
struct Traj_ {
  typedef Traj_<ContainerAllocator> Type;

  Traj_()
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , vx(0.0)
  , vy(0.0)
  , vz(0.0)
  , acc_x(0.0)
  , acc_y(0.0)
  , acc_z(0.0)
  , stop(0.0)
  , mode(0)
  , use_sensor(false)
  {
  }

  Traj_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , vx(0.0)
  , vy(0.0)
  , vz(0.0)
  , acc_x(0.0)
  , acc_y(0.0)
  , acc_z(0.0)
  , stop(0.0)
  , mode(0)
  , use_sensor(false)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _z_type;
  double z;

  typedef double _vx_type;
  double vx;

  typedef double _vy_type;
  double vy;

  typedef double _vz_type;
  double vz;

  typedef double _acc_x_type;
  double acc_x;

  typedef double _acc_y_type;
  double acc_y;

  typedef double _acc_z_type;
  double acc_z;

  typedef double _stop_type;
  double stop;

  typedef int32_t _mode_type;
  int32_t mode;

  typedef uint8_t _use_sensor_type;
  uint8_t use_sensor;


private:
  static const char* __s_getDataType_() { return "opticalflow_msgs/Traj"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "2247a0f85eea2ff3978d67b9faa207e8"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 x\n\
float64 y\n\
float64 z\n\
float64 vx\n\
float64 vy\n\
float64 vz\n\
float64 acc_x\n\
float64 acc_y\n\
float64 acc_z\n\
float64 stop\n\
int32 mode\n\
bool use_sensor\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    ros::serialization::serialize(stream, z);
    ros::serialization::serialize(stream, vx);
    ros::serialization::serialize(stream, vy);
    ros::serialization::serialize(stream, vz);
    ros::serialization::serialize(stream, acc_x);
    ros::serialization::serialize(stream, acc_y);
    ros::serialization::serialize(stream, acc_z);
    ros::serialization::serialize(stream, stop);
    ros::serialization::serialize(stream, mode);
    ros::serialization::serialize(stream, use_sensor);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    ros::serialization::deserialize(stream, z);
    ros::serialization::deserialize(stream, vx);
    ros::serialization::deserialize(stream, vy);
    ros::serialization::deserialize(stream, vz);
    ros::serialization::deserialize(stream, acc_x);
    ros::serialization::deserialize(stream, acc_y);
    ros::serialization::deserialize(stream, acc_z);
    ros::serialization::deserialize(stream, stop);
    ros::serialization::deserialize(stream, mode);
    ros::serialization::deserialize(stream, use_sensor);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    size += ros::serialization::serializationLength(z);
    size += ros::serialization::serializationLength(vx);
    size += ros::serialization::serializationLength(vy);
    size += ros::serialization::serializationLength(vz);
    size += ros::serialization::serializationLength(acc_x);
    size += ros::serialization::serializationLength(acc_y);
    size += ros::serialization::serializationLength(acc_z);
    size += ros::serialization::serializationLength(stop);
    size += ros::serialization::serializationLength(mode);
    size += ros::serialization::serializationLength(use_sensor);
    return size;
  }

  typedef boost::shared_ptr< ::opticalflow_msgs::Traj_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opticalflow_msgs::Traj_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Traj
typedef  ::opticalflow_msgs::Traj_<std::allocator<void> > Traj;

typedef boost::shared_ptr< ::opticalflow_msgs::Traj> TrajPtr;
typedef boost::shared_ptr< ::opticalflow_msgs::Traj const> TrajConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::opticalflow_msgs::Traj_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::opticalflow_msgs::Traj_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace opticalflow_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::opticalflow_msgs::Traj_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::opticalflow_msgs::Traj_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::opticalflow_msgs::Traj_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2247a0f85eea2ff3978d67b9faa207e8";
  }

  static const char* value(const  ::opticalflow_msgs::Traj_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2247a0f85eea2ff3ULL;
  static const uint64_t static_value2 = 0x978d67b9faa207e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::opticalflow_msgs::Traj_<ContainerAllocator> > {
  static const char* value() 
  {
    return "opticalflow_msgs/Traj";
  }

  static const char* value(const  ::opticalflow_msgs::Traj_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::opticalflow_msgs::Traj_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 vx\n\
float64 vy\n\
float64 vz\n\
float64 acc_x\n\
float64 acc_y\n\
float64 acc_z\n\
float64 stop\n\
int32 mode\n\
bool use_sensor\n\
\n\
";
  }

  static const char* value(const  ::opticalflow_msgs::Traj_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::opticalflow_msgs::Traj_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::opticalflow_msgs::Traj_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.vx);
    stream.next(m.vy);
    stream.next(m.vz);
    stream.next(m.acc_x);
    stream.next(m.acc_y);
    stream.next(m.acc_z);
    stream.next(m.stop);
    stream.next(m.mode);
    stream.next(m.use_sensor);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Traj_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opticalflow_msgs::Traj_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::opticalflow_msgs::Traj_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
    s << indent << "vz: ";
    Printer<double>::stream(s, indent + "  ", v.vz);
    s << indent << "acc_x: ";
    Printer<double>::stream(s, indent + "  ", v.acc_x);
    s << indent << "acc_y: ";
    Printer<double>::stream(s, indent + "  ", v.acc_y);
    s << indent << "acc_z: ";
    Printer<double>::stream(s, indent + "  ", v.acc_z);
    s << indent << "stop: ";
    Printer<double>::stream(s, indent + "  ", v.stop);
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
    s << indent << "use_sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_sensor);
  }
};


} // namespace message_operations
} // namespace ros

#endif // OPTICALFLOW_MSGS_MESSAGE_TRAJ_H

