/* Auto-generated by genmsg_cpp for file /home/root/ros/quadrotor_msgs/msg/Corrections.msg */
#ifndef QUADROTOR_MSGS_MESSAGE_CORRECTIONS_H
#define QUADROTOR_MSGS_MESSAGE_CORRECTIONS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct Corrections_ {
  typedef Corrections_<ContainerAllocator> Type;

  Corrections_()
  : kf_correction(0.0)
  , angle_corrections()
  {
    angle_corrections.assign(0.0);
  }

  Corrections_(const ContainerAllocator& _alloc)
  : kf_correction(0.0)
  , angle_corrections()
  {
    angle_corrections.assign(0.0);
  }

  typedef double _kf_correction_type;
  double kf_correction;

  typedef boost::array<double, 2>  _angle_corrections_type;
  boost::array<double, 2>  angle_corrections;


  ROS_DEPRECATED uint32_t get_angle_corrections_size() const { return (uint32_t)angle_corrections.size(); }
private:
  static const char* __s_getDataType_() { return "quadrotor_msgs/Corrections"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "61e86887a75fe520847d3256306360f5"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 kf_correction\n\
float64[2] angle_corrections\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, kf_correction);
    ros::serialization::serialize(stream, angle_corrections);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, kf_correction);
    ros::serialization::deserialize(stream, angle_corrections);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(kf_correction);
    size += ros::serialization::serializationLength(angle_corrections);
    return size;
  }

  typedef boost::shared_ptr< ::quadrotor_msgs::Corrections_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::Corrections_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Corrections
typedef  ::quadrotor_msgs::Corrections_<std::allocator<void> > Corrections;

typedef boost::shared_ptr< ::quadrotor_msgs::Corrections> CorrectionsPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::Corrections const> CorrectionsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::quadrotor_msgs::Corrections_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::quadrotor_msgs::Corrections_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::quadrotor_msgs::Corrections_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::quadrotor_msgs::Corrections_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::Corrections_<ContainerAllocator> > {
  static const char* value() 
  {
    return "61e86887a75fe520847d3256306360f5";
  }

  static const char* value(const  ::quadrotor_msgs::Corrections_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x61e86887a75fe520ULL;
  static const uint64_t static_value2 = 0x847d3256306360f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::Corrections_<ContainerAllocator> > {
  static const char* value() 
  {
    return "quadrotor_msgs/Corrections";
  }

  static const char* value(const  ::quadrotor_msgs::Corrections_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::Corrections_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 kf_correction\n\
float64[2] angle_corrections\n\
\n\
";
  }

  static const char* value(const  ::quadrotor_msgs::Corrections_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::quadrotor_msgs::Corrections_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::Corrections_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.kf_correction);
    stream.next(m.angle_corrections);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Corrections_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::Corrections_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::quadrotor_msgs::Corrections_<ContainerAllocator> & v) 
  {
    s << indent << "kf_correction: ";
    Printer<double>::stream(s, indent + "  ", v.kf_correction);
    s << indent << "angle_corrections[]" << std::endl;
    for (size_t i = 0; i < v.angle_corrections.size(); ++i)
    {
      s << indent << "  angle_corrections[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angle_corrections[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_CORRECTIONS_H

