/* Auto-generated by genmsg_cpp for file /home/root/ros/sonar/msg/Range.msg */
#ifndef SONAR_MESSAGE_RANGE_H
#define SONAR_MESSAGE_RANGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace sonar
{
template <class ContainerAllocator>
struct Range_ {
  typedef Range_<ContainerAllocator> Type;

  Range_()
  : header()
  , min_range(0.0)
  , max_range(0.0)
  , range(0.0)
  {
  }

  Range_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , min_range(0.0)
  , max_range(0.0)
  , range(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _min_range_type;
  float min_range;

  typedef float _max_range_type;
  float max_range;

  typedef float _range_type;
  float range;


private:
  static const char* __s_getDataType_() { return "sonar/Range"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "36fb80612fdb39b24648681823b5f0a8"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
float32 min_range\n\
float32 max_range\n\
float32 range\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, min_range);
    ros::serialization::serialize(stream, max_range);
    ros::serialization::serialize(stream, range);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, min_range);
    ros::serialization::deserialize(stream, max_range);
    ros::serialization::deserialize(stream, range);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(min_range);
    size += ros::serialization::serializationLength(max_range);
    size += ros::serialization::serializationLength(range);
    return size;
  }

  typedef boost::shared_ptr< ::sonar::Range_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sonar::Range_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Range
typedef  ::sonar::Range_<std::allocator<void> > Range;

typedef boost::shared_ptr< ::sonar::Range> RangePtr;
typedef boost::shared_ptr< ::sonar::Range const> RangeConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::sonar::Range_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::sonar::Range_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace sonar

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::sonar::Range_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::sonar::Range_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::sonar::Range_<ContainerAllocator> > {
  static const char* value() 
  {
    return "36fb80612fdb39b24648681823b5f0a8";
  }

  static const char* value(const  ::sonar::Range_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x36fb80612fdb39b2ULL;
  static const uint64_t static_value2 = 0x4648681823b5f0a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::sonar::Range_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sonar/Range";
  }

  static const char* value(const  ::sonar::Range_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::sonar::Range_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 min_range\n\
float32 max_range\n\
float32 range\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::sonar::Range_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::sonar::Range_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::sonar::Range_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::sonar::Range_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.min_range);
    stream.next(m.max_range);
    stream.next(m.range);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Range_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sonar::Range_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::sonar::Range_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "min_range: ";
    Printer<float>::stream(s, indent + "  ", v.min_range);
    s << indent << "max_range: ";
    Printer<float>::stream(s, indent + "  ", v.max_range);
    s << indent << "range: ";
    Printer<float>::stream(s, indent + "  ", v.range);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SONAR_MESSAGE_RANGE_H

