(cl:in-package opticalflow_msgs-msg)
(cl:export '(X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
          VICON_X-VAL
          VICON_X
          VICON_Y-VAL
          VICON_Y
          VICON_Z-VAL
          VICON_Z
          VICON_VX-VAL
          VICON_VX
          VICON_VY-VAL
          VICON_VY
          VICON_VZ-VAL
          VICON_VZ
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
))