(cl:in-package opticalflow_msgs-msg)
(cl:export '(X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          VX-VAL
          VX
          VY-VAL
          VY
          VICON_VX-VAL
          VICON_VX
          VICON_VY-VAL
          VICON_VY
          SENSOR_VX-VAL
          SENSOR_VX
          SENSOR_VY-VAL
          SENSOR_VY
          VZ-VAL
          VZ
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          DES_X-VAL
          DES_X
          DES_Y-VAL
          DES_Y
          DES_Z-VAL
          DES_Z
          DES_VX-VAL
          DES_VX
          DES_VY-VAL
          DES_VY
          DES_VZ-VAL
          DES_VZ
          DES_ROLL-VAL
          DES_ROLL
          DES_PITCH-VAL
          DES_PITCH
          DES_YAW-VAL
          DES_YAW
          DES_ACCX-VAL
          DES_ACCX
          DES_ACCY-VAL
          DES_ACCY
          DES_ACCZ-VAL
          DES_ACCZ
))